name: publish

on:
  push:
    - master

jobs:
  building:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0
      with:
      node-version: '12.x'

    - name: Build
      run: npm install && npm run build

    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
         SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
         ARGS: "-rltgoDzvO --delete"
         SOURCE: "dist/"
         REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
         REMOTE_USER: ${{ secrets.REMOTE_USER }}
         TARGET: ${{ secrets.REMOTE_TARGET }}
